language: python
python:
    - "3.3"
    - "3.4"
    - "3.5"
services:
    - postgresql
addons:
    postgresql: "9.3"
env:
    global:
        - DJANGO_SETTINGS_MODULE="rotd.settings.ci"
sudo: false
install:
    - pip install -r requirements/test.txt
    - pip install coveralls
before_script:
    # set up postgresql
    - psql -c "CREATE DATABASE wzive_ci" -U postgres
    # start xvfb
    - "export DISPLAY=:99.0"
    - "sh -e /etc/init.d/xvfb start"
    - sleep 3 # allow xvfb some time to start
script:
    - coverage run -p manage.py test recipes common
    - coverage run -p manage.py test functional_tests
after_success:
    - "coverage combine && coveralls"
